### ISSUE TITLE
Driver for X5000 Ethernet PHY is missing

### ISSUE THREAD

**Issue by dair-dc** [chzigotzky/kernels#3]
The X5000 kernel configuration does not include driver for Ethernet PHY of X5000 board (Micrel KSZ9021): "CONFIG_MICREL_PHY is not set". This prevents sending data onto the wire.

**Comment by chzigotzky** [comment]
Thanks a lot for the hint.

The X5000 uses the KSZ9021RN PHYs.

I will add CONFIG_MICREL_PHY to the next kernel.

**Comment by dair-dc** [comment]
I used your configuration for 6.6.30, and the network works with CONFIG_MICREL_PHY, but something is still wrong, and time to time long connections (like SSH sessions) freeze, Tx queue grows, but no real transmission. I still do not know what triggers this issue.

**Comment by chzigotzky** [comment]
Thank you very much for your bug report.

I compiled a new kernel with CONFIG_MICREL_PHY=y for the X5000 today.

Could you please test it?

Download: [v6.11.0-rc3-2](https://github.com/chzigotzky/kernels/releases/tag/v6.11.0-rc3-2)

**Comment by dair-dc** [comment]
Looks working for me. I've been using it for 1.5 h, do not observe freezes/disconnects yet.

**Comment by chzigotzky** [comment]
Thank you for testing. :-)

**Comment by chzigotzky** [comment]
Great news! :-)

Trevor wrote:
> Christian,

> I've just successfully installed RC3 on my X5000/40 running Fienix.

> This is the first time I've that Ethernet worked from a cold start without me having to remove and re-insert the Ethernet cable. With all previous Kernels I had to remove and re-connect the Ethernet cable for networking to be initiated. 

> With RC3 Ethernet worked OK from a cold boot.

> Still testing.

> Regards,

> Trevor

**Comment by chzigotzky** [comment]
> Looks working for me. I've been using it for 1.5 h, do not observe freezes/disconnects yet.

Many thanks for solving the issue with the DPAA Ethernet. If you know other improvements, then please open a new ticket. Thank you.
